### PR TITLE
'babareko test'

### PR DESCRIPTION
**Pull request by SvetaRomashko**

### CODE REVIEW

**Review by i3oi3ka — DISMISSED** [review]
lgfm

**Review by LiudmilaZhdanok — DISMISSED** [review]
If you delete "TestServise" your coverege in sonar will be large. Probably)

**Comment by SvetaRomashko** [comment]
> If you delete "TestServise" your coverege in sonar will be large. Probably)

ok.

**Review by olgaz-skiba — APPROVED** [review]

**Review by LiudmilaZhdanok — APPROVED** [review]
Lgfm

**Review by AnastasiaSheremet — APPROVED** [review]

**Pull request merged**
